# Generated by Django 6.0.6 on 2026-06-28 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Course Price')),
                ('instructor_name', models.CharField(max_length=255, verbose_name='Instructor Name')),
                ('designation', models.CharField(max_length=255, verbose_name='Designation')),
                ('instructor_bio', models.TextField(verbose_name='Instructor Bio')),
                ('certification', models.CharField(max_length=255, verbose_name='Certification')),
                ('duration', models.CharField(max_length=100, verbose_name='Duration (e.g., 4 Months / 48 Hours)')),
                ('version', models.CharField(max_length=50, verbose_name='Version (e.g., Offline/Online)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Course Thumbnail')),
                ('course_overview', models.TextField(verbose_name='Course Overview')),
                ('what_you_will_learn', models.JSONField(default=list, help_text="Format: [{'category': '...', 'topics': ['...', '...']}]", verbose_name='What You Will Learn')),
                ('who_can_join', models.JSONField(default=list, help_text="Format: ['Student', 'Job Seeker']", verbose_name='Who Can Join')),
                ('course_benefits', models.JSONField(default=list, help_text="Format: ['Benefit 1', 'Benefit 2']", verbose_name='Course Benefits')),
                ('career_opportunities', models.JSONField(default=list, help_text="Format: ['Opportunity 1', 'Opportunity 2']", verbose_name='Career Opportunities')),
                ('why_choose_me', models.JSONField(default=list, help_text="Format: [{'title': '...', 'description': '...'}]", verbose_name='Why Choose Me')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('business_or_topic', models.CharField(blank=True, help_text='তিনি কি শিখতে চান নাকি বিজনেস গ্রোথ সার্ভিস চান', max_length=255, null=True)),
                ('message', models.TextField()),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Mark as Contacted (Saptak checked this?)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Course Title')),
                ('thumbnail', models.ImageField(upload_to='courses/')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Course Fee')),
                ('duration', models.CharField(blank=True, help_text='e.g., 3 Months', max_length=100, null=True)),
                ('total_lectures', models.IntegerField(blank=True, default=24, null=True)),
                ('what_you_will_learn', models.JSONField(blank=True, help_text="লিস্ট আকারে লিখুন, যেমন: ['SEO Basic', 'Keyword Research']", null=True)),
                ('course_benefits', models.JSONField(blank=True, help_text='লিস্ট আকারে লিখুন', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL এর জন্য (যেমন: digital-marketing-tips)', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('digital_marketing', 'Digital Marketing'), ('freelancing_hacks', 'Freelancing Hacks'), ('corporate_growth', 'Corporate Growth')], max_length=50)),
                ('thumbnail', models.ImageField(upload_to='blogs/')),
                ('content', models.TextField(help_text='ব্লগের মূল কন্টেন্ট')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Complete Business Growth Solution', max_length=255)),
                ('service_type', models.CharField(blank=True, help_text='e.g., Premium Consultation Blueprint', max_length=100, null=True)),
                ('service_overview', models.TextField(blank=True, help_text='আমার এই সার্ভিসের মূল উদ্দেশ্য বা সংক্ষিপ্ত বিবরণ', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('description', models.TextField(blank=True, help_text='সার্ভিসের ধরন (যেমন: Customized Solution Only)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Student/Client Name')),
                ('designation', models.CharField(blank=True, help_text='যেমন: Student of Batch 5 বা CEO of TechCorp', max_length=150, null=True)),
                ('testimonial_type', models.CharField(choices=[('certificate', 'Student Certificate'), ('experience', 'Client Experience Certificate')], max_length=20)),
                ('comment', models.TextField(help_text='তারা Saptak বা Drive to Traffic সম্পর্কে কি বলেছেন')),
                ('document_image', models.ImageField(blank=True, help_text='সার্টিফিকেট বা এক্সপেরিয়েন্স লেটারের ছবি', null=True, upload_to='testimonials/')),
                ('rating', models.IntegerField(default=5, help_text='১ থেকে ৫ এর মধ্যে রেটিং')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_type', models.CharField(choices=[('included_services', 'Included Services'), ('what_we_do', 'What I Do / Core Expertise'), ('working_process', 'My Strategic Working Process'), ('who_is_service_for', 'Who is this Service For'), ('why_choose_us', 'Why Choose Me')], max_length=50, verbose_name='Tab Type')),
                ('content', models.JSONField(verbose_name='Content (JSON)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_items', to='blogs.service', verbose_name='Select Service')),
            ],
        ),
    ]
